### ISSUE TITLE
Unicode symbol completion

### ISSUE THREAD

**Issue by texastoland** [nwolverson/purescript-ide-purescript-core#4]
Random idea to suggest completions for the set of non-keyboard symbols defined in the parser?

**Comment by nwolverson** [comment]
YM replacing `->` with `→`, `forall` with `∀`?

**Comment by texastoland** [comment]
Also `⇒`, `⇐`, `←`, `∷`, <s>and `λ`</s> (not merged with purescript/purescript#1847). See https://github.com/purescript/purescript/blob/master/examples/passing/UnicodeType.purs.

**Comment by garyb** [comment]
I use Atom snippets to do this, I prefer that to having them autocomplete without me choosing whether I want them or not. When I was using Sublime I had it up to do it automatically, but found it annoying.

From my `snippets.cson`:

``` cson
'.source.purescript':

  'Function arrow':
    'prefix': '->'
    'body': '→'

  'Do arrow':
    'prefix': '<-'
    'body': '←'

  'Constraint arrow':
    'prefix': '=>'
    'body': '⇒'

  'Implies arrow':
    'prefix': '<='
    'body': '⇐'

  'Type annotation':
    'prefix': '::'
    'body': '∷'

  'Forall':
    'prefix': 'forall'
    'body': '∀'
```

**Comment by nwolverson** [comment]
Code also supports user snippets:

https://code.visualstudio.com/docs/customization/userdefinedsnippets#_creating-your-own-snippets

We can add these to the plugins, but that will make them appear regardless of preference (at least the usual way).

**Comment by texastoland** [comment]
That does make more sense. I'll raise a ticket about API.

**Comment by nwolverson** [comment]
Closing due to consensus (ie gary). This could easily be a standalone extension if someone wants it.
