### ISSUE TITLE
Add support for changing polling parameter

### ISSUE THREAD

**Issue by cebaa** [nwolverson/purescript-ide-purescript-core#9]
I see you added support for `--polling` via https://github.com/kRITZCREEK/purescript-psc-ide/pull/39/commits/a39cb951cf9a113867b2e041e33fd962755ffd8c, but looks like this defaults to false and cannot be re-configured in purescript-ide-purescript-core?

**Comment by nwolverson** [comment]
I see no reason not to add this, but I'm curious, are you using `purescript-ide-purescript-core` directly?

**Comment by cebaa** [comment]
@nwolverson Thanks! No, I'm using the standard https://github.com/nwolverson/vscode-ide-purescript. So I guess that also needs added as a setting there?

**Comment by nwolverson** [comment]
Yes, indeed. Though you might also be interested in `--editor-mode` which I think has made it already.

**Comment by cebaa** [comment]
@nwolverson Thanks! `--editor-mode`  seems to do the work! :1st_place_medal:
